name: Check Code

on:
    pull_request:

jobs:
    Check-Code:
        runs-on: ubuntu-latest
        environment: Development
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Set up Python 3.10
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install tox and any other packages
              run: pip install tox

            - name: Run tox
              run: tox -c tox.ini -e py310
